<?php

namespace Database\Seeders;

use App\Models\Customer;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CustomerSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * The customers on 売上一覧表_2026年09月.xlsx, one per 顧客NO. (used as the code), in 顧客NO.
     * order. Company-type marks (㈱・㈲・(株)・合同会社) are dropped, and so are the notes after a
     * name that split one customer into several invoices (e.g. PIA㈱（ドンキ）, ㈱拓洋 三洋) —
     * those are told apart on each answer by 作成区分 instead.
     *
     * @var list<array{code: string, name: string}>
     */
    private const CUSTOMERS = [
        ['code' => '2', 'name' => 'アイネクスト'],
        ['code' => '4', 'name' => '朝日食品'],
        ['code' => '6', 'name' => 'アミティ'],
        ['code' => '8', 'name' => 'アートフィールド'],
        ['code' => '11', 'name' => 'アポワテック'],
        ['code' => '21', 'name' => 'アクシネットジャパンインク'],
        ['code' => '23', 'name' => 'アイレ'],
        ['code' => '25', 'name' => 'アニマリベラ'],
        ['code' => '29', 'name' => 'アイセイ'],
        ['code' => '101', 'name' => 'インタービア'],
        ['code' => '103', 'name' => 'いちもんめ'],
        ['code' => '105', 'name' => 'イザナギ'],
        ['code' => '107', 'name' => 'インターメスティック'],
        ['code' => '113', 'name' => 'イン・フィールド'],
        ['code' => '201', 'name' => 'ウエニ貿易'],
        ['code' => '205', 'name' => 'ウィット'],
        ['code' => '303', 'name' => 'エボルテック'],
        ['code' => '304', 'name' => 'MXロジスティクス'],
        ['code' => '305', 'name' => 'エスアールシー'],
        ['code' => '306', 'name' => 'エンマバイシクルワークス'],
        ['code' => '319', 'name' => 'SSQQB'],
        ['code' => '321', 'name' => 'anytee'],
        ['code' => '324', 'name' => 'MIジャパン'],
        ['code' => '326', 'name' => 'エヌ・コバヤシ'],
        ['code' => '331', 'name' => 'エアロセンス'],
        ['code' => '401', 'name' => 'オルガニコ'],
        ['code' => '402', 'name' => 'オーシー'],
        ['code' => '403', 'name' => 'オルガインターナショナル'],
        ['code' => '408', 'name' => 'オスト'],
        ['code' => '501', 'name' => '韓国のりジャパン'],
        ['code' => '502', 'name' => 'KAZUコーポレーション'],
        ['code' => '507', 'name' => 'カーサリコルド'],
        ['code' => '601', 'name' => 'キャトル・ペンシー'],
        ['code' => '602', 'name' => 'キャラバン'],
        ['code' => '603', 'name' => '協栄産業'],
        ['code' => '604', 'name' => 'ギフト・アンド・カンパニー'],
        ['code' => '701', 'name' => 'グッドフェイス'],
        ['code' => '702', 'name' => 'グッドファーマーズ'],
        ['code' => '706', 'name' => 'クリエイション'],
        ['code' => '710', 'name' => 'クニミツベンダー東京'],
        ['code' => '801', 'name' => 'ケーワイコーポレーション'],
        ['code' => '802', 'name' => '京葉アローズ'],
        ['code' => '805', 'name' => 'ケーシー企画'],
        ['code' => '900', 'name' => '国分'],
        ['code' => '901', 'name' => 'コムテック'],
        ['code' => '905', 'name' => 'コンフェックス'],
        ['code' => '1003', 'name' => '三洋'],
        ['code' => '1004', 'name' => 'サクセスアジア'],
        ['code' => '1005', 'name' => 'サンクス'],
        ['code' => '1006', 'name' => 'ザリーンジャパン'],
        ['code' => '1008', 'name' => '佐藤商店'],
        ['code' => '1019', 'name' => 'sacri'],
        ['code' => '1101', 'name' => 'JO factory'],
        ['code' => '1104', 'name' => 'ジャストドゥイット'],
        ['code' => '1106', 'name' => 'シュタイン'],
        ['code' => '1117', 'name' => 'SYNCRE'],
        ['code' => '1119', 'name' => 'JR貨物ロジ・ソリューションズ'],
        ['code' => '1201', 'name' => 'スタンバイ'],
        ['code' => '1203', 'name' => 'スタンダップ'],
        ['code' => '1204', 'name' => 'スパイラルキュート'],
        ['code' => '1209', 'name' => 'スイッチ・オン'],
        ['code' => '1210', 'name' => 'STARDUST HD'],
        ['code' => '1214', 'name' => 'スタイレム瀧定大阪'],
        ['code' => '1303', 'name' => '先進医療研究所'],
        ['code' => '1403', 'name' => 'ゾフ'],
        ['code' => '1501', 'name' => '大洋製薬'],
        ['code' => '1502', 'name' => '拓洋'],
        ['code' => '1504', 'name' => 'ダッシュ'],
        ['code' => '1509', 'name' => '太平電機'],
        ['code' => '1601', 'name' => '中央サトー販売'],
        ['code' => '1603', 'name' => 'チームゼロ'],
        ['code' => '1604', 'name' => '中央化学産業'],
        ['code' => '1702', 'name' => 'ツインクル'],
        ['code' => '1801', 'name' => 'ティーエス企画'],
        ['code' => '1803', 'name' => 'ティースケール'],
        ['code' => '1805', 'name' => 'TMトランスポート'],
        ['code' => '1813', 'name' => 'Dicita'],
        ['code' => '1908', 'name' => '東和合成工業'],
        ['code' => '1910', 'name' => 'Dragon Network'],
        ['code' => '1916', 'name' => 'トータルディスプレイ'],
        ['code' => '2005', 'name' => '中島製茶'],
        ['code' => '2101', 'name' => '日新電気照明'],
        ['code' => '2102', 'name' => '日本紙運輸倉庫'],
        ['code' => '2106', 'name' => '日本システムズ'],
        ['code' => '2109', 'name' => 'NIOMA'],
        ['code' => '2302', 'name' => 'ネクストレード'],
        ['code' => '2403', 'name' => 'NOZZA SERVICE'],
        ['code' => '2502', 'name' => 'バナナスピリッツ'],
        ['code' => '2504', 'name' => 'パラマウント・グローバル・ジャパン'],
        ['code' => '2505', 'name' => 'ハールド'],
        ['code' => '2511', 'name' => '博雲堂'],
        ['code' => '2513', 'name' => 'HACHI BRANDING'],
        ['code' => '2601', 'name' => 'PIA'],
        ['code' => '2602', 'name' => '樋口物流サービス'],
        ['code' => '2603', 'name' => 'ビープレジャー'],
        ['code' => '2604', 'name' => 'PSロジテック'],
        ['code' => '2605', 'name' => 'ヒビキスパイス'],
        ['code' => '2606', 'name' => 'ビオ・マガジン'],
        ['code' => '2608', 'name' => 'ビーディ・ラボ'],
        ['code' => '2612', 'name' => 'ビッグ・ブリッジ'],
        ['code' => '2613', 'name' => 'BEAUTEX'],
        ['code' => '2614', 'name' => 'ピュア'],
        ['code' => '2615', 'name' => '日の出運輸'],
        ['code' => '2701', 'name' => 'フクヤ'],
        ['code' => '2703', 'name' => 'フロムアイズ'],
        ['code' => '2704', 'name' => 'ブルーゲート'],
        ['code' => '2706', 'name' => 'ブルーイング'],
        ['code' => '2707', 'name' => 'ファイブカセット'],
        ['code' => '2710', 'name' => 'プレステージ'],
        ['code' => '2717', 'name' => 'フリークス'],
        ['code' => '2718', 'name' => 'フレックス'],
        ['code' => '2719', 'name' => 'Fun Standard'],
        ['code' => '2720', 'name' => 'フコックス'],
        ['code' => '2901', 'name' => 'ホダカ'],
        ['code' => '3201', 'name' => 'ムーブ'],
        ['code' => '3203', 'name' => 'ムラカミ'],
        ['code' => '3403', 'name' => '百道'],
        ['code' => '3502', 'name' => '山香煎餅本舗'],
        ['code' => '3601', 'name' => 'ユニット'],
        ['code' => '3603', 'name' => 'U\'s'],
        ['code' => '3701', 'name' => '横浜ゴム'],
        ['code' => '3802', 'name' => 'ラッド'],
        ['code' => '3903', 'name' => 'リード'],
        ['code' => '4001', 'name' => 'ルラシオン'],
        ['code' => '4101', 'name' => 'レダ'],
        ['code' => '4102', 'name' => 'LENSSIS'],
        ['code' => '4301', 'name' => 'ワンダーランド'],
        ['code' => '4305', 'name' => 'ワイシー'],
    ];

    public function run(): void
    {
        foreach (self::CUSTOMERS as $index => $customer) {
            Customer::updateOrCreate(
                ['code' => $customer['code']],
                ['name' => $customer['name'], 'sort_order' => ($index + 1) * 10, 'is_active' => true],
            );
        }
    }
}
